#!/bin/bash

# Ensure AWS CLI is installed and configured with the correct region and permissions

# Define the output file
ENV_FILE=".env"

# Clear the file if it already exists
> $ENV_FILE

# Add each environment variable from SSM to the .env file
PARAMETERS=("APP_ENV" "QUEUE_CONNECTION" "SQS_QUEUE" "APP_NAME" "APP_KEY" "APP_DEBUG" "APP_URL" "LOG_CHANNEL" "LOG_DEPRECATIONS_CHANNEL" "LOG_LEVEL" "DB_CONNECTION" "DB_HOST" "DB_PORT" "DB_DATABASE" "DB_USERNAME" "DB_PASSWORD" "BROADCAST_DRIVER" "CACHE_DRIVER" "FILESYSTEM_DISK" "SESSION_DRIVER" "SESSION_LIFETIME" "MEMCACHED_HOST" "REDIS_HOST" "REDIS_PASSWORD" "REDIS_PORT" "MAIL_MAILER" "MAIL_HOST" "MAIL_PORT" "MAIL_USERNAME" "MAIL_PASSWORD" "MAIL_ENCRYPTION" "MAIL_FROM_ADDRESS" "MAIL_FROM_NAME" "AWS_USE_PATH_STYLE_ENDPOINT" "PUSHER_PORT" "PUSHER_SCHEME" "PUSHER_APP_CLUSTER" "VITE_APP_NAME" "VITE_PUSHER_APP_KEY" "VITE_PUSHER_HOST" "VITE_PUSHER_PORT" "VITE_PUSHER_SCHEME" "VITE_PUSHER_APP_CLUSTER" "DISCORD_TOKEN" "DISCORD_PUBLIC_KEY" "ID_FOLDER_GBA" "ID_FOLDER_GBC" "ID_FOLDER_GB" "ID_FOLDER_NES" "ID_FOLDER_SNES" "ID_FOLDER_64" "ID_FOLDER_GAMECUBE" "ID_FOLDER_DS" "ID_FOLDER_PSX" "ID_FOLDER_PS2" "ID_FOLDER_PSP" "ID_FOLDER_3DS" "ID_FOLDER_DREAMCAST" "ID_FOLDER_WII" "ID_FOLDER_SWITCH" "ID_FOLDER_GENESIS" "SAGIRI_TOKEN" "ASSET_URL" "SECRET_NAME" "OWNER" "REPO_NAME" "SESSION_DOMAIN" "SANCTUM_STATEFUL_DOMAINS")

for PARAM in "${PARAMETERS[@]}"; do
  VALUE=$(aws ssm get-parameter --name "/aigisbot/prod/$PARAM" --with-decryption --query "Parameter.Value" --output text --region us-east-1)
  echo "$PARAM=$VALUE" >> $ENV_FILE
done


echo ".env file has been generated."
