service: serverless-aigisbot

provider:
    name: aws
    # The AWS region in which to deploy (us-east-1 is the default)
    region: us-east-1
    # Environment variables
    stage: ${opt:stage, 'dev'}  # Default to 'dev' if not specified
    environment:
        APP_ENV: production # Or use ${sls:stage} if you want the environment to match the stage
        QUEUE_CONNECTION: sqs
        SQS_QUEUE: ${construct:jobs.queueUrl}
        APP_NAME: "Aigisbot"
        APP_KEY: ${ssm:/aigisbot/${self:provider.stage}/APP_KEY}
        APP_DEBUG: ${ssm:/aigisbot/${self:provider.stage}/APP_DEBUG}
        APP_URL: ${ssm:/aigisbot/${self:provider.stage}/APP_URL}
        LOG_CHANNEL: ${ssm:/aigisbot/${self:provider.stage}/LOG_CHANNEL}
        LOG_DEPRECATIONS_CHANNEL: ${ssm:/aigisbot/${self:provider.stage}/LOG_DEPRECATIONS_CHANNEL}
        LOG_LEVEL: ${ssm:/aigisbot/${self:provider.stage}/LOG_LEVEL}
        DB_CONNECTION: ${ssm:/aigisbot/${self:provider.stage}/DB_CONNECTION}
        DB_HOST: ${ssm:/aigisbot/${self:provider.stage}/DB_HOST}
        DB_PORT: ${ssm:/aigisbot/${self:provider.stage}/DB_PORT}
        DB_DATABASE: ${ssm:/aigisbot/${self:provider.stage}/DB_DATABASE}
        DB_USERNAME: ${ssm:/aigisbot/${self:provider.stage}/DB_USERNAME}
        DB_PASSWORD: ${ssm:/aigisbot/${self:provider.stage}/DB_PASSWORD}
        BROADCAST_DRIVER: ${ssm:/aigisbot/${self:provider.stage}/BROADCAST_DRIVER}
        CACHE_DRIVER: ${ssm:/aigisbot/${self:provider.stage}/CACHE_DRIVER}
        FILESYSTEM_DISK: ${ssm:/aigisbot/${self:provider.stage}/FILESYSTEM_DISK}
        SESSION_DRIVER: ${ssm:/aigisbot/${self:provider.stage}/SESSION_DRIVER}
        SESSION_LIFETIME: ${ssm:/aigisbot/${self:provider.stage}/SESSION_LIFETIME}
        MEMCACHED_HOST: ${ssm:/aigisbot/${self:provider.stage}/MEMCACHED_HOST}
        REDIS_HOST: ${ssm:/aigisbot/${self:provider.stage}/REDIS_HOST}
        REDIS_PASSWORD: ${ssm:/aigisbot/${self:provider.stage}/REDIS_PASSWORD}
        REDIS_PORT: ${ssm:/aigisbot/${self:provider.stage}/REDIS_PORT}
        MAIL_MAILER: ${ssm:/aigisbot/${self:provider.stage}/MAIL_MAILER}
        MAIL_HOST: ${ssm:/aigisbot/${self:provider.stage}/MAIL_HOST}
        MAIL_PORT: ${ssm:/aigisbot/${self:provider.stage}/MAIL_PORT}
        MAIL_USERNAME: ${ssm:/aigisbot/${self:provider.stage}/MAIL_USERNAME}
        MAIL_PASSWORD: ${ssm:/aigisbot/${self:provider.stage}/MAIL_PASSWORD}
        MAIL_ENCRYPTION: ${ssm:/aigisbot/${self:provider.stage}/MAIL_ENCRYPTION}
        MAIL_FROM_ADDRESS: ${ssm:/aigisbot/${self:provider.stage}/MAIL_FROM_ADDRESS}
        MAIL_FROM_NAME: ${ssm:/aigisbot/${self:provider.stage}/MAIL_FROM_NAME}
        # AWS_ACCESS_KEY_ID: ${ssm:/aigisbot/${self:provider.stage}/AWS_ACCESS_KEY_ID}
        # AWS_SECRET_ACCESS_KEY: ${ssm:/aigisbot/${self:provider.stage}/AWS_SECRET_ACCESS_KEY}
        # AWS_DEFAULT_REGION: ${ssm:/aigisbot/${self:provider.stage}/AWS_DEFAULT_REGION}
        AWS_BUCKET: 
          Ref: MyS3Bucket
        AWS_USE_PATH_STYLE_ENDPOINT: ${ssm:/aigisbot/${self:provider.stage}/AWS_USE_PATH_STYLE_ENDPOINT}
        # PUSHER_APP_ID: ${ssm:/aigisbot/${self:provider.stage}/PUSHER_APP_ID}
        # PUSHER_APP_KEY: ${ssm:/aigisbot/${self:provider.stage}/PUSHER_APP_KEY}
        # PUSHER_APP_SECRET: ${ssm:/aigisbot/${self:provider.stage}/PUSHER_APP_SECRET}
        # PUSHER_HOST: ${ssm:/aigisbot/${self:provider.stage}/PUSHER_HOST}
        PUSHER_PORT: ${ssm:/aigisbot/${self:provider.stage}/PUSHER_PORT}
        PUSHER_SCHEME: ${ssm:/aigisbot/${self:provider.stage}/PUSHER_SCHEME}
        PUSHER_APP_CLUSTER: ${ssm:/aigisbot/${self:provider.stage}/PUSHER_APP_CLUSTER}
        VITE_APP_NAME: ${ssm:/aigisbot/${self:provider.stage}/VITE_APP_NAME}
        VITE_PUSHER_APP_KEY: ${ssm:/aigisbot/${self:provider.stage}/VITE_PUSHER_APP_KEY}
        VITE_PUSHER_HOST: ${ssm:/aigisbot/${self:provider.stage}/VITE_PUSHER_HOST}
        VITE_PUSHER_PORT: ${ssm:/aigisbot/${self:provider.stage}/VITE_PUSHER_PORT}
        VITE_PUSHER_SCHEME: ${ssm:/aigisbot/${self:provider.stage}/VITE_PUSHER_SCHEME}
        VITE_PUSHER_APP_CLUSTER: ${ssm:/aigisbot/${self:provider.stage}/VITE_PUSHER_APP_CLUSTER}
        DISCORD_TOKEN: ${ssm:/aigisbot/${self:provider.stage}/DISCORD_TOKEN}
        DISCORD_PUBLIC_KEY: ${ssm:/aigisbot/${self:provider.stage}/DISCORD_PUBLIC_KEY}
        DISCORD_BOT_ID: ${ssm:/aigisbot/${self:provider.stage}/DISCORD_BOT_ID}
        # GOOGLE_AUTH: ${ssm:/aigisbot/${self:provider.stage}/GOOGLE_AUTH}
        ID_FOLDER_GBA: ${ssm:/aigisbot/${self:provider.stage}/ID_FOLDER_GBA}
        ID_FOLDER_GBC: ${ssm:/aigisbot/${self:provider.stage}/ID_FOLDER_GBC}
        ID_FOLDER_GB: ${ssm:/aigisbot/${self:provider.stage}/ID_FOLDER_GB}
        ID_FOLDER_NES: ${ssm:/aigisbot/${self:provider.stage}/ID_FOLDER_NES}
        ID_FOLDER_SNES: ${ssm:/aigisbot/${self:provider.stage}/ID_FOLDER_SNES}
        ID_FOLDER_64: ${ssm:/aigisbot/${self:provider.stage}/ID_FOLDER_64}
        ID_FOLDER_GAMECUBE: ${ssm:/aigisbot/${self:provider.stage}/ID_FOLDER_GAMECUBE}
        ID_FOLDER_DS: ${ssm:/aigisbot/${self:provider.stage}/ID_FOLDER_DS}
        ID_FOLDER_PSX: ${ssm:/aigisbot/${self:provider.stage}/ID_FOLDER_PSX}
        ID_FOLDER_PS2: ${ssm:/aigisbot/${self:provider.stage}/ID_FOLDER_PS2}
        ID_FOLDER_PSP: ${ssm:/aigisbot/${self:provider.stage}/ID_FOLDER_PSP}
        ID_FOLDER_3DS: ${ssm:/aigisbot/${self:provider.stage}/ID_FOLDER_3DS}
        ID_FOLDER_DREAMCAST: ${ssm:/aigisbot/${self:provider.stage}/ID_FOLDER_DREAMCAST}
        ID_FOLDER_WII: ${ssm:/aigisbot/${self:provider.stage}/ID_FOLDER_WII}
        ID_FOLDER_SWITCH: ${ssm:/aigisbot/${self:provider.stage}/ID_FOLDER_SWITCH}
        ID_FOLDER_GENESIS: ${ssm:/aigisbot/${self:provider.stage}/ID_FOLDER_GENESIS}
        SAGIRI_TOKEN: ${ssm:/aigisbot/${self:provider.stage}/SAGIRI_TOKEN}
        ASSET_URL: ${ssm:/aigisbot/${self:provider.stage}/ASSET_URL}
        SECRET_NAME: ${ssm:/aigisbot/${self:provider.stage}/SECRET_NAME}
        OWNER: ${ssm:/aigisbot/${self:provider.stage}/OWNER}
        REPO_NAME: ${ssm:/aigisbot/${self:provider.stage}/REPO_NAME}
        SESSION_DOMAIN: ${ssm:/aigisbot/${self:provider.stage}/SESSION_DOMAIN}
        SANCTUM_STATEFUL_DOMAINS: ${ssm:/aigisbot/${self:provider.stage}/SANCTUM_STATEFUL_DOMAINS}
        MI_INDICADOR_BASE_URL: ${ssm:/aigisbot/${self:provider.stage}/MI_INDICADOR_BASE_URL}
        TCG_SCRAPER_BASE_URL: ${ssm:/aigisbot/${self:provider.stage}/TCG_SCRAPER_BASE_URL}


    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:*
        Resource:
          - arn:aws:s3:::*
package:
    # Files and directories to exclude from deployment
    patterns:
        - '!node_modules/**'
        - '!public/storage'
        - '!resources/assets/**'
        - '!storage/**'
        - '!tests/**'

plugins:
    # We need to include the Bref plugin
    - ./vendor/bref/bref
    - serverless-lift
    - ./vendor/bref/extra-php-extensions
    - serverless-plugin-warmup


functions:

    # This function runs the Laravel website/API
    web:
        handler: public/index.php
        runtime: php-83-fpm
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        events:
            - httpApi: '*'
            - schedule:
                rate: rate(5 minutes)
                input:
                    warmer: true
        layers:
            - ${bref-extra:gd-php-83}
        architecture: arm64

        

    # This function lets us run artisan commands in Lambda
    artisan:
        handler: artisan
        runtime: php-83-console
        timeout: 720 # in seconds
        layers:
            - ${bref-extra:gd-php-83}
        # Uncomment to also run the scheduler every minute
        events:
           - schedule:
                 rate: rate(1 minute)
                 input: '"schedule:run"'
        


constructs:
    website:
        type: server-side-website
        assets:
            '/js/*': public/js
            '/css/*': public/css
            '/favicon.ico': public/favicon.ico
            '/robots.txt': public/robots.txt
            '/vendor/telescope/*': public/vendor/telescope

        domain: 'roms.aigisbot.online'
        certificate: '${ssm:/aigisbot/${self:provider.stage}/ACM_CERT_ARN}'


    jobs:
        type: queue
        worker:
            handler: Bref\LaravelBridge\Queue\QueueHandler
            runtime: php-83
            timeout: 60 # seconds
            layers:
            - ${bref-extra:gd-php-83}


resources:
  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: aigisbot-media-v2